#banner:
#  charset: UTF-8
#  location: classpath:banner.txt
#
#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:postgresql://192.168.3.230:5432/pm
#    username: pm
#    password: aaaaaaaa
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      pool-name: pool-lxl
#      maximum-pool-size: 50
#      minimum-idle: 10
#
#
#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  type-aliases-package: cn.qegoo.search.domain
#
