banner:
  charset: UTF-8
  location: classpath:banner.txt

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: pool-lxl
      connectionTestQuery: SELECT 1
      maximum-pool-size: 50
      minimum-idle: 10


mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: cn.qegoo.search.domain

